spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class: com.cj.jdbc.Driver
  sql:
    init:
      mode: always
      continue-on-error: true
# paging
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 200

# date format
  mvc:
    format:
      date-time: iso
      date: iso
# context path config
server:
  servlet:
    context-path: /api/v1
cross-delivery:
# security config
  security:
    jwtCookieName: accessToken
    jwtRefreshCookieName: refreshToken
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 900000
    jwtRefreshExpirationHr: 24
    maxAgeSeconds: 86400
